TPT-4560: Add merge readiness check (#911)
Co-authored-by: Zhiwei Liang <121905282+zliang-akamai@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,6 +3,7 @@ on:
   workflow_dispatch: null
   push:
   pull_request:
+    types: [opened, synchronize, reopened, labeled, unlabeled]
 jobs:
   docker-build:
     runs-on: ubuntu-latest
@@ -58,6 +59,11 @@ jobs:
       - name: run linter
         run: make lint
 
+      - name: Check Merge Readiness
+        if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'do-not-merge')
+        run: |
+          echo "::error::This PR is labeled 'do-not-merge'."
+          exit 1
   unit-tests-on-ubuntu:
     runs-on: ubuntu-latest
     strategy:
