test: upload xml reports to test account's obj storage (#517)
Co-authored-by: Zhiwei Liang <121905282+zliang-akamai@users.noreply.github.com>
Co-authored-by: Lena Garber <114949949+lgarber-akamai@users.noreply.github.com>

diff --git a/.github/workflows/e2e-suite.yml b/.github/workflows/e2e-suite.yml
--- a/.github/workflows/e2e-suite.yml
+++ b/.github/workflows/e2e-suite.yml
@@ -36,6 +36,20 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Run the integration test suite
-        run: make testint
+        run: |
+          timestamp=$(date +'%Y%m%d%H%M')
+          report_filename="${timestamp}_cli_test_report.xml"
+          status=0
+          if ! pytest -m tests/integration --disable-warnings --junitxml="${report_filename}"; then
+            echo "Tests failed, but attempting to upload results anyway"
+          fi
         env:
           LINODE_CLI_TOKEN: ${{ secrets.LINODE_TOKEN }}
+
+      - name: Upload test results
+        run: |
+          linode-cli obj --cluster us-southeast-1 put "${report_filename}" dx-test-results
+        env:
+          LINODE_CLI_TOKEN: ${{ secrets.SHARED_DX_TOKEN }}
+          LINODE_CLI_OBJ_ACCESS_KEY: ${{ secrets.LINODE_CLI_OBJ_ACCESS_KEY }}
+          LINODE_CLI_OBJ_SECRET_KEY: ${{ secrets.LINODE_CLI_OBJ_SECRET_KEY }}
